language: node_js
node_js:
- '12'
services:
- docker
before_install:
- docker pull docker.elastic.co/elasticsearch/elasticsearch:7.6.0
- docker run -d  -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.6.0
- npm install -g npm-install-peers
before_script:
- npm-install-peers
script:
- npm run test
